databases:
  - name: blockbuster
    databaseName: rentdb
    user: marta

services:
  - type: web
    name: blockbuster
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rentdb
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false